server {
    listen 80;
    server_name goreact.local;
    root /usr/share/nginx/html;
    index index.html;

    # هر درخواستی که با /api شروع بشه رو به سرویس todo-api (داخل داکر) پروکسی کن
    location /api/ {
        proxy_pass http://todo-api:4000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # بقیه درخواست‌ها رو هندل کن (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}
